MAX_FILE_SIZE_MB: int = 50
PREVIEW_CHAR_LIMIT: int = 200
QUALITY_THRESHOLD_HIGH: float = 80.0
QUALITY_THRESHOLD_LOW: float = 50.0
DEFAULT_TXT_ENCODING: str = "utf-8"
SUPPORTED_EXTENSIONS: list[str] = [".pdf", ".txt"]
MAX_WORKERS: int = 4